export const ADD_STAFFS = 'ADD_STAFFS';
export const LOADING_STAFFS = 'LOADING_STAFFS';
export const FAILED_STAFFS = 'FAILED_STAFFS';
export const ADD_NEW_STAFF = 'ADD_NEW_STAFF';

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const LOADING_DEPARTMENTS = 'LOADING_DEPARTMENTS';
export const FAILED_DEPARTMENTS = 'FAILED_DEPARTMENTS';

export const ADD_SALARIES = 'ADD_SALARIES';
export const LOADING_SALARIES = 'LOADING_SALARIES'
export const FAILED_SALARIES = 'FAILED_SALARIES'

export const DELETE_STAFF = 'DELETE_STAFF';
export const EDIT_STAFF = 'EDIT_STAFF';